version: "3"

services:
  docusaurus:
    build: .
    tty: true
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./docs:/app/docs
      - ./website:/app/website
    working_dir: /app/website
    environment:
      - 'GIT_USER=${GIT_USER}'
      - 'CURRENT_BRANCH=${CURRENT_BRANCH}'
      - 'USE_SSH=${USE_SSH}'
